- hosts : main-master
  become: true
  var_files:
    - /home/ubuntu/ha-ip.yml

  tasks:

    - name : Initialize our cluster
      shell: sudo kubeadm init --pod-network-cidr="192.168.0.0/16"  --cri-socket /run/cri-docker.sock --upload-certs --control-plane-endpoint {{HAPROXY1}}:6443
      register: output

    - name : storing logs and generating tokens for future purpose
      local_action: copy content={{ output.stdout }} dest = "/tmp/token" mode=0777

    - name : make directory and copy required file to it
      shell: |
        sudo su -c 'mkdir -p $HOME/.kube' ubuntu
        sudo su -c 'sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config' ubuntu
        sudo su -c 'sudo chown $(id -u):$(id -g) $HOME/.kube/config' ubuntu

    - name : fetch the config file from main-master to ansible host
      run_once: true
      fetch: src=/home/ubuntu/.kube/config dest=/home/ubuntu/ flat=yes