---
 - hosts: haproxy1
   become: true
   tasks:  

    - name: Deleting Previous Deployment to stage-shop
      shell: sudo su -c "kubectl delete -f staging-complete.yaml" ubuntu
      ignore_errors: true 
      args:
       chdir: US-Team-Sock-Shop-App-Repo/deploy/kubernetes

    - name: Deploying Latest Features to stage-shop
      shell: sudo su -c "kubectl apply -f staging-complete.yam" ubuntu
      args:
       chdir: US-Team-Sock-Shop-App-Repo/deploy/kubernetes